In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
import time
import numpy as np
from loguru import logger
import warnings
warnings.filterwarnings("ignore")

#data loading
csv_info = '../../Data/important/info_eth_100dscam.csv'
csv_liq = '../../Data/important/liq_eth_100d_scam.csv'


df_info = pd.read_csv(csv_info)
df_liq = pd.read_csv(csv_liq)


pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

print('Done data loading')

Done data loading

In [266]:
df_liq

                id  block_number  log_index                                   transaction_hash            timestamp exchange_name contract_version                                pool_address                               token_address  pool_balance category                              sender_address   amount_token  token_price                  created_at
0         19606198      16298365         46  0x1d8ab20f6b4ca53a27c784c24c30e4dc644f32841f30...  2022-12-31 02:05:23       uniswap               v2  0x235CF969D8BbfC4B1c95FB289D93a1F7754162Dd  0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2  1.003861e+00     sell  0x7b6963E95b65aCF3B9d31BcD0a389D92b9defA9D      -0.001130  1186.930000  2025-05-01 07:49:36.854649
1         19606199      16298365         56  0x1d8ab20f6b4ca53a27c784c24c30e4dc644f32841f30...  2022-12-31 02:05:23       uniswap               v2  0x235CF969D8BbfC4B1c95FB289D93a1F7754162Dd  0x29a5eeF038a6A474d218a4e281924f24e990adF7  3.861669e+07  deposit  0x7b6963E95b65aCF3B9d31BcD0a389D92b9defA9D    3293.667583     0.000030  2025-05-01 07:49:36.854649
2         19606200      16298365         56  0x1d8ab20f6b4ca53a27c784c24c30e4dc644f32841f30...  2022-12-31 02:05:23       uniswap               v2  0x235CF969D8BbfC4B1c95FB289D93a1F7754162Dd  0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2  1.003946e+00  deposit  0x7b6963E95b65aCF3B9d31BcD0a389D92b9defA9D       0.000086  1186.930000   2025-05-01 07:49:36.85465
3         19606201      16298365         62  0x1d8ab20f6b4ca53a27c784c24c30e4dc644f32841f30...  2022-12-31 02:05:23       uniswap               v2  0x235CF969D8BbfC4B1c95FB289D93a1F7754162Dd  0x29a5eeF038a6A474d218a4e281924f24e990adF7  3.916594e+07     sell  0x7b6963E95b65aCF3B9d31BcD0a389D92b9defA9D  549244.476000     0.000030  2025-05-01 07:49:36.854651
4         19606202      16298365         62  0x1d8ab20f6b4ca53a27c784c24c30e4dc644f32841f30...  2022-12-31 02:05:23       uniswap               v2  0x235CF969D8BbfC4B1c95FB289D93a1F7754162Dd  0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2  9.899092e-01     sell  0x7b6963E95b65aCF3B9d31BcD0a389D92b9defA9D      -0.014037  1186.930000  2025-05-01 07:49:36.854651
...            ...           ...        ...                                                ...                  ...           ...              ...                                         ...                                         ...           ...      ...                                         ...            ...          ...                         ...
34192762  19606193      16298361         46  0xb4880f848264a680ba62a58523cb3858e319969b3cb4...  2022-12-31 02:04:35       uniswap               v2  0x235CF969D8BbfC4B1c95FB289D93a1F7754162Dd  0x29a5eeF038a6A474d218a4e281924f24e990adF7  3.767924e+07  deposit  0x98DD72112fF1E88366dFd097793bA1bd1d4dBD37    1964.471594     0.000032  2025-05-01 07:49:36.854645
34192763  19606194      16298361         46  0xb4880f848264a680ba62a58523cb3858e319969b3cb4...  2022-12-31 02:04:35       uniswap               v2  0x235CF969D8BbfC4B1c95FB289D93a1F7754162Dd  0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2  1.028674e+00  deposit  0x98DD72112fF1E88366dFd097793bA1bd1d4dBD37       0.000054  1187.630000  2025-05-01 07:49:36.854646
34192764  19606195      16298361         52  0xb4880f848264a680ba62a58523cb3858e319969b3cb4...  2022-12-31 02:04:35       uniswap               v2  0x235CF969D8BbfC4B1c95FB289D93a1F7754162Dd  0x29a5eeF038a6A474d218a4e281924f24e990adF7  3.856984e+07     sell  0x98DD72112fF1E88366dFd097793bA1bd1d4dBD37  890602.513603     0.000032  2025-05-01 07:49:36.854647
34192765  19606196      16298361         52  0xb4880f848264a680ba62a58523cb3858e319969b3cb4...  2022-12-31 02:04:35       uniswap               v2  0x235CF969D8BbfC4B1c95FB289D93a1F7754162Dd  0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2  1.004991e+00     sell  0x98DD72112fF1E88366dFd097793bA1bd1d4dBD37      -0.023683  1187.630000  2025-05-01 07:49:36.854647
34192766  19606197      16298365         46  0x1d8ab20f6b4ca53a27c784c24c30e4dc644f32841f30...  2022-12-31 02:05:23       uniswap               v2  0x235CF969D8BbfC4B1c95FB289D93a1F7754162Dd  0x29a5eeF038a6A474d218a4e281924f24e990adF7  3.861340e+07     sell  0x7b6963E95b65aCF3B9d31BcD0a389D92b9defA9D   43558.042435     0.000030  2025-05-01 07:49:36.854648

[34192767 rows x 15 columns]

In [ ]:
pool_list = ['0x2aC4aeAd22A1694405dA5ceBa7D2F78A0fd49fe5', 
             '0x52A587d480fB23c9d121D72b00825D50909302AE', 
             '0xC5a4209cf7B573127Bbf4fD9B03F5c04Fe8f65EC',
             '0x6621C4106bd1062eF4aaA6191a03b7Cc724e5Fd1',
             '0xc1e65CB4f442441e01e6563fA56C1dDCdD703232',
             '0xc78a6a91eC734E65f2bE58ECA63Fceae36785Ca6',
             '0x0F89Ecf47905b2c1e24a65032cc2FA2d2df4092d',
             '0x136c6edfE2Ad09E8bd228648bbced8442d3BE561',
             '0xff59529A5bDf9dC2e0d2A9E67652D079C0C81395',
             '0x6e390E53714A2f2f10080e015Aa2f1df06481288',
             '0x7446dcA634f3Ad8783C7423c22205D93C3ad97B4',
             '0xD87193D8aC3F14f39c872A907Dc0FfdBcd32CB38',
             '0xA817EA3D6CE5D4943eC328E015a42B509d48d042',
             '0x6F742514f74dC7743A1F9F97c617ECbC48CA20b0',
             '0x802c33C102F492F3E7AE9C01672694ef7b650122',
             '0x1E1921D65837a264e7B8D00c60295Bb806d0BdD2',
             '0x8effAFA22aDa759B423394757CAacC6735Dae871',
             '0xD9f1bD9B90c1A0c3D86021Da6634AF06a74e74c0',
             '0xF2b9E2E99e9913EE1e45fc7C62Cb1310E7FBbcDE',
             '0x9F84B751aE5b3a6e0205dD77E52359EF7B6D445d'
             ]

a = df_info[df_info['pool_address'].isin(pool_list)]
b = df_liq[df_liq['pool_address'].isin(pool_list)]

20
20

In [271]:
a.to_csv('../../Data/preliminary/scam_report_info.csv', index=False)
b.to_csv('../../Data/preliminary/scam_report_liq.csv', index=False)

In [245]:
df_info[df_info['unverified_symbol'].str.contains(code, na=False)]

Empty DataFrame
Columns: [token_created_time, pool_created_time, pool_address, token_paired_address, verified_decimals, token_address, name, unverified_symbol, token_owner, id, fail]
Index: []